organization:
  name: AD Tech

permission:
  enabled: true

proxy:

auth:
  providers:
    guest: {}

app:
  title: Backstage App
  baseUrl: http://localhost:9003

backend:
  title: Backstage Backend
  baseUrl: http://localhost:7007
  listen:
    port: 7007
  reading:
    allow:
      - host: raw.githubusercontent.com
  csp:
    connect-src: ["'self'", 'http:', 'https:']
  cors:
    origin: http://localhost:9003
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  database:
    client: better-sqlite3
    connection: ':memory:'
  # workingDirectory: /tmp
  # auth:
  #   keys:
  #     - secret: ${BACKEND_SECRET}

kubernetes:

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}

techdocs:
  builder: 'local' # local | external
  generator:
    runIn: 'docker' # local | docker
  publisher:
    type: 'local' # local | googleGcs | awsS3

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location, User, Group]
  locations:
    - type: file
      target: ./org.yaml
    - type: url
      target: https://raw.githubusercontent.com/AlvaroDavi5/Node_BackEnd_Boilerplate-TypeScript/refs/heads/main/catalog-info.yml
  useUrlReadersSearch: true
